const mongoose =require("mongoose");
const videoSchema = new mongoose.Schema({
  title:{
        type:String,
        required:true
    },
    video:{
      type:String,
      required:true
    },
    image:{
      type:String,
      required:true
    },
    description:{
      type:String,
      required:true
    },
    category:{
      type:String,
      required:true
    },
    movies:{
       type:String,
       required:true
    },
    adult:{
      type:Boolean,
      required:true
    },
    home_category:{
      type:String,
      required:true
    },
    durantion:{
      type:String,
      required:true
    }
 
})
module.exports=mongoose.model("Video",videoSchema);
